[default]

UVICORN_SERVER_HOST = "0.0.0.0"
UVICORN_SERVER_PORT = 10000
UVICORN_SERVER_LOG_LEVEL = "info"
UVICORN_SERVER_ACCESS_LOG = true
UVICORN_SERVER_RELOAD = true
UVICORN_SERVER_FACTORY = true

LOGGER_CONFIG = "configs/logger_cfg.yaml"
ENCODING = "utf-8"